language: python
sudo: false
python: 2.7
env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py34-lint
  - TOX_ENV=py27-lint-readme
  - TOX_ENV=py27-lint-docs
  - TOX_ENV=py27-quick
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py27-lint-docstrings

install:
  # Setup git to allow git operations.
  - git config --global user.name "Travis Test User"
  - git config --global user.email "planemo_test@galaxyproject.org"
  - pip install tox coveralls

matrix:
  allow_failures:
    - env: TOX_ENV=py34
    - env: TOX_ENV=py27-lint-docstrings

script: PLANEMO_ENABLE_POSTGRES_TESTS=1 PLANEMO_SKIP_CWLTOOL_TESTS=1 tox -e $TOX_ENV

after_success:
  - coveralls

services:
  - postgresql