# Config file for automatic testing at travis-ci.org

language: python

python:
#  - "3.4"
  - "2.7"
  - "2.6"
# pypy option seems very unreliable lately, lots of errors downloading dependencies.
#  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install -r requirements.txt
  - pip install pyflakes flake8 readme

# command to run tests, e.g. python setup.py test
script: make lint && make test && if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then true; else make lint-readme; fi

